server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note_mgt_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Adeshina@100

  jpa:
    hibernate:
      ddl-auto: update


    database-platform: org.hibernate.dialect.MySQL8Dialect

